/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package akka.android;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int chopstick_horz=0x7f020000;
        public static final int chopstick_vert=0x7f020001;
        public static final int debasish=0x7f020002;
        public static final int irmo=0x7f020003;
        public static final int jonas=0x7f020004;
        public static final int martin=0x7f020005;
        public static final int viktor=0x7f020006;
    }
    public static final class id {
        public static final int bottom=0x7f050011;
        public static final int bottomleft=0x7f050012;
        public static final int bottomright=0x7f050017;
        public static final int hakker1=0x7f050003;
        public static final int hakker1left=0x7f050004;
        public static final int hakker1right=0x7f050005;
        public static final int hakker2=0x7f05000f;
        public static final int hakker2left=0x7f050010;
        public static final int hakker2right=0x7f05000e;
        public static final int hakker3=0x7f050014;
        public static final int hakker3left=0x7f050015;
        public static final int hakker3right=0x7f050016;
        public static final int hakker4=0x7f05000a;
        public static final int hakker4left=0x7f050009;
        public static final int hakker4right=0x7f05000b;
        public static final int hakker5=0x7f050019;
        public static final int hakker5left=0x7f05001a;
        public static final int hakker5right=0x7f05001b;
        public static final int middle=0x7f050006;
        public static final int midleft=0x7f050007;
        public static final int midright=0x7f05000c;
        public static final int rel01=0x7f050002;
        public static final int rel02=0x7f05000d;
        public static final int rel03=0x7f050013;
        public static final int rel04=0x7f050008;
        public static final int rel05=0x7f050018;
        public static final int top=0x7f050001;
        public static final int widget103=0x7f050000;
    }
    public static final class layout {
        public static final int mainlayout=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
